name: 'kotlinx-benchmark-table'
description: "An Action to take info from kotlinx-benchmark outputs and display them in a table as a pull request comment"
author: 'boswelja'
branding:
  icon: 'bar-chart-2'
  color: 'purple'
inputs:
  benchmark-results:
    description: "The benchmark result files"
    required: true
outputs:
  benchmark-table:
    description: "The markdown-formatted table for the benchmarks"
runs:
  using: 'node20'
  main: 'dist/index.js'